// <auto-generated />
using Client_Ranker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Client_Ranker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608235439_AddSecurityFields_Fix")]
    partial class AddSecurityFields_Fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("Client_Ranker.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiamondThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastClosedMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastClosedYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PesosPorPunto")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatinumThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecoveryPin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SilverThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupervisorPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Client_Ranker.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentMonthSpending")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentMonthVisits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LastMonthSpending")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Client_Ranker.Models.MonthlySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BronzeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiamondCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoldCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlatinumCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SilverCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UniqueCustomers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MonthlySummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
